var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/board/[boardId]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__6d19ee53._.js")
R.c("server/chunks/ssr/_0efddc1b._.js")
R.c("server/chunks/ssr/_708a4628._.js")
R.c("server/chunks/ssr/[root-of-the-server]__91accbc1._.js")
R.c("server/chunks/ssr/node_modules_63dba3f8._.js")
R.c("server/chunks/ssr/node_modules_7cb79fa0._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__11fa4345._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_board_[boardId]_page_actions_c1fe7391.js")
R.m(86658)
module.exports=R.m(86658).exports
