var R=require("../../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/board/[boardId]/task/[taskId]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__bb88033a._.js")
R.c("server/chunks/ssr/_0efddc1b._.js")
R.c("server/chunks/ssr/_bf8268f2._.js")
R.c("server/chunks/ssr/[root-of-the-server]__91accbc1._.js")
R.c("server/chunks/ssr/node_modules_63dba3f8._.js")
R.c("server/chunks/ssr/node_modules_7cb79fa0._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__11fa4345._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_board_[boardId]_task_[taskId]_page_actions_f72c623e.js")
R.m(80770)
module.exports=R.m(80770).exports
